---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: reverse 
spec:
  replicas: 3
  selector:
    matchLabels:
      name: reverse
  template:
    metadata:
      labels:
        name: reverse
    spec:
      containers:
      - name: application
        image: tb15/reverse:tag1
        imagePullPolicy: IfNotPresent
        ports:
          - containerPort: 8090
        livenessProbe:
          httpGet:
            path: /
            port: 8090
          initialDelaySeconds: 3
          periodSeconds: 3 
        readinessProbe:
          httpGet:
            path: /
            port: 8090
          initialDelaySeconds: 3
          periodSeconds: 3 
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: random 
spec:
  replicas: 3
  selector:
    matchLabels:
      name: random
  template:
    metadata:
      labels:
        name: random 
    spec:
      containers:
      - name: application
        image: tb15/random:tag1
        imagePullPolicy: IfNotPresent
        ports:
          - containerPort: 8080 
        livenessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 3
          periodSeconds: 3 
        readinessProbe:
          httpGet:
            path: /
            port: 8090 
          initialDelaySeconds: 3
          periodSeconds: 3 
