---
apiVersion: v1
kind: Service
metadata:
  name: random 
spec:
  type: LoadBalancer
  ports:
  - name: http
    port: 80
    targetPort: 8080 
  selector:
    name: random 
---
apiVersion: v1
kind: Service
metadata:
  name: reverse
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 80
    targetPort: 8090
  selector:
    name: reverse 

